//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.IMABS;

[assembly: RegisterDocumentType(SocialMedia.CLASS_NAME, typeof(SocialMedia))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type SocialMedia.
	/// </summary>
	public partial class SocialMedia : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.SocialMedia";


		/// <summary>
		/// The instance of the class that provides extended API for working with SocialMedia fields.
		/// </summary>
		private readonly SocialMediaFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SocialMediaID.
		/// </summary>
		[DatabaseIDField]
		public int SocialMediaID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SocialMediaID"), 0);
			}
			set
			{
				SetValue("SocialMediaID", value);
			}
		}


		/// <summary>
		/// Platform.
		/// </summary>
		[DatabaseField]
		public string SocialMediaPlatform
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialMediaPlatform"), @"");
			}
			set
			{
				SetValue("SocialMediaPlatform", value);
			}
		}


		/// <summary>
		/// Logo.
		/// </summary>
		[DatabaseField]
		public Guid SocialMediaLogo
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("SocialMediaLogo"), Guid.Empty);
			}
			set
			{
				SetValue("SocialMediaLogo", value);
			}
		}


		/// <summary>
		/// Redirection Url.
		/// </summary>
		[DatabaseField]
		public string SocialMediaURL
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialMediaURL"), @"");
			}
			set
			{
				SetValue("SocialMediaURL", value);
			}
		}


		/// <summary>
		/// Social Media Class.
		/// </summary>
		[DatabaseField]
		public string SocialMediaClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialMediaClass"), @"");
			}
			set
			{
				SetValue("SocialMediaClass", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SocialMedia fields.
		/// </summary>
		[RegisterProperty]
		public SocialMediaFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SocialMedia fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SocialMediaFields : AbstractHierarchicalObject<SocialMediaFields>
		{
			/// <summary>
			/// The content item of type SocialMedia that is a target of the extended API.
			/// </summary>
			private readonly SocialMedia mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SocialMediaFields" /> class with the specified content item of type SocialMedia.
			/// </summary>
			/// <param name="instance">The content item of type SocialMedia that is a target of the extended API.</param>
			public SocialMediaFields(SocialMedia instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SocialMediaID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SocialMediaID;
				}
				set
				{
					mInstance.SocialMediaID = value;
				}
			}


			/// <summary>
			/// Platform.
			/// </summary>
			public string Platform
			{
				get
				{
					return mInstance.SocialMediaPlatform;
				}
				set
				{
					mInstance.SocialMediaPlatform = value;
				}
			}


			/// <summary>
			/// Logo.
			/// </summary>
			public DocumentAttachment Logo
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("SocialMediaLogo");
				}
			}


			/// <summary>
			/// Redirection Url.
			/// </summary>
			public string URL
			{
				get
				{
					return mInstance.SocialMediaURL;
				}
				set
				{
					mInstance.SocialMediaURL = value;
				}
			}


			/// <summary>
			/// Social Media Class.
			/// </summary>
			public string Class
			{
				get
				{
					return mInstance.SocialMediaClass;
				}
				set
				{
					mInstance.SocialMediaClass = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SocialMedia" /> class.
		/// </summary>
		public SocialMedia() : base(CLASS_NAME)
		{
			mFields = new SocialMediaFields(this);
		}

		#endregion
	}
}