//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(SubNavigation.CLASS_NAME, typeof(SubNavigation))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type SubNavigation.
	/// </summary>
	public partial class SubNavigation : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.SubNavigation";


		/// <summary>
		/// The instance of the class that provides extended API for working with SubNavigation fields.
		/// </summary>
		private readonly SubNavigationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SubNavigationID.
		/// </summary>
		[DatabaseIDField]
		public int SubNavigationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SubNavigationID"), 0);
			}
			set
			{
				SetValue("SubNavigationID", value);
			}
		}


		/// <summary>
		/// Sub Navigation Item Name.
		/// </summary>
		[DatabaseField]
		public string SubNavigationItemName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SubNavigationItemName"), @"");
			}
			set
			{
				SetValue("SubNavigationItemName", value);
			}
		}


		/// <summary>
		/// Sub Navigation Item Url.
		/// </summary>
		[DatabaseField]
		public string SubNavigationItemUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SubNavigationItemUrl"), @"");
			}
			set
			{
				SetValue("SubNavigationItemUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SubNavigation fields.
		/// </summary>
		[RegisterProperty]
		public SubNavigationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SubNavigation fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SubNavigationFields : AbstractHierarchicalObject<SubNavigationFields>
		{
			/// <summary>
			/// The content item of type SubNavigation that is a target of the extended API.
			/// </summary>
			private readonly SubNavigation mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SubNavigationFields" /> class with the specified content item of type SubNavigation.
			/// </summary>
			/// <param name="instance">The content item of type SubNavigation that is a target of the extended API.</param>
			public SubNavigationFields(SubNavigation instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SubNavigationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SubNavigationID;
				}
				set
				{
					mInstance.SubNavigationID = value;
				}
			}


			/// <summary>
			/// Sub Navigation Item Name.
			/// </summary>
			public string ItemName
			{
				get
				{
					return mInstance.SubNavigationItemName;
				}
				set
				{
					mInstance.SubNavigationItemName = value;
				}
			}


			/// <summary>
			/// Sub Navigation Item Url.
			/// </summary>
			public string ItemUrl
			{
				get
				{
					return mInstance.SubNavigationItemUrl;
				}
				set
				{
					mInstance.SubNavigationItemUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SubNavigation" /> class.
		/// </summary>
		public SubNavigation() : base(CLASS_NAME)
		{
			mFields = new SubNavigationFields(this);
		}

		#endregion
	}
}