//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ServiceTemplateTitle.CLASS_NAME, typeof(ServiceTemplateTitle))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type ServiceTemplateTitle.
	/// </summary>
	public partial class ServiceTemplateTitle : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.ServiceTemplateTitle";


		/// <summary>
		/// The instance of the class that provides extended API for working with ServiceTemplateTitle fields.
		/// </summary>
		private readonly ServiceTemplateTitleFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProductCategoryTemplateTitleID.
		/// </summary>
		[DatabaseIDField]
		public int ServiceTemplateTitleID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ServiceTemplateTitleID"), 0);
			}
			set
			{
				SetValue("ServiceTemplateTitleID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Service panel title.
		/// </summary>
		[DatabaseField]
		public string ServicePanelTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ServicePanelTitle"), @"");
			}
			set
			{
				SetValue("ServicePanelTitle", value);
			}
		}


		/// <summary>
		/// Brand title.
		/// </summary>
		[DatabaseField]
		public string BrandTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrandTitle"), @"");
			}
			set
			{
				SetValue("BrandTitle", value);
			}
		}


		/// <summary>
		/// Contact us title.
		/// </summary>
		[DatabaseField]
		public string ContactUsTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsTitle"), @"");
			}
			set
			{
				SetValue("ContactUsTitle", value);
			}
		}


		/// <summary>
		/// Service title.
		/// </summary>
		[DatabaseField]
		public string ServiceListTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ServiceListTitle"), @"");
			}
			set
			{
				SetValue("ServiceListTitle", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ServiceTemplateTitle fields.
		/// </summary>
		[RegisterProperty]
		public ServiceTemplateTitleFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ServiceTemplateTitle fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ServiceTemplateTitleFields : AbstractHierarchicalObject<ServiceTemplateTitleFields>
		{
			/// <summary>
			/// The content item of type ServiceTemplateTitle that is a target of the extended API.
			/// </summary>
			private readonly ServiceTemplateTitle mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ServiceTemplateTitleFields" /> class with the specified content item of type ServiceTemplateTitle.
			/// </summary>
			/// <param name="instance">The content item of type ServiceTemplateTitle that is a target of the extended API.</param>
			public ServiceTemplateTitleFields(ServiceTemplateTitle instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProductCategoryTemplateTitleID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ServiceTemplateTitleID;
				}
				set
				{
					mInstance.ServiceTemplateTitleID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Service panel title.
			/// </summary>
			public string ServicePanelTitle
			{
				get
				{
					return mInstance.ServicePanelTitle;
				}
				set
				{
					mInstance.ServicePanelTitle = value;
				}
			}


			/// <summary>
			/// Brand title.
			/// </summary>
			public string BrandTitle
			{
				get
				{
					return mInstance.BrandTitle;
				}
				set
				{
					mInstance.BrandTitle = value;
				}
			}


			/// <summary>
			/// Contact us title.
			/// </summary>
			public string ContactUsTitle
			{
				get
				{
					return mInstance.ContactUsTitle;
				}
				set
				{
					mInstance.ContactUsTitle = value;
				}
			}


			/// <summary>
			/// Service title.
			/// </summary>
			public string ServiceListTitle
			{
				get
				{
					return mInstance.ServiceListTitle;
				}
				set
				{
					mInstance.ServiceListTitle = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ServiceTemplateTitle" /> class.
		/// </summary>
		public ServiceTemplateTitle() : base(CLASS_NAME)
		{
			mFields = new ServiceTemplateTitleFields(this);
		}

		#endregion
	}
}