//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Brand.CLASS_NAME, typeof(Brand))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type Brand.
	/// </summary>
	public partial class Brand : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.Brand";


		/// <summary>
		/// The instance of the class that provides extended API for working with Brand fields.
		/// </summary>
		private readonly BrandFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BrandCategoryID.
		/// </summary>
		[DatabaseIDField]
		public int BrandID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BrandID"), 0);
			}
			set
			{
				SetValue("BrandID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public Guid Image
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Image"), Guid.Empty);
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Redirection Url.
		/// </summary>
		[DatabaseField]
		public string RedirectionUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RedirectionUrl"), @"");
			}
			set
			{
				SetValue("RedirectionUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Brand fields.
		/// </summary>
		[RegisterProperty]
		public BrandFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Brand fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BrandFields : AbstractHierarchicalObject<BrandFields>
		{
			/// <summary>
			/// The content item of type Brand that is a target of the extended API.
			/// </summary>
			private readonly Brand mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BrandFields" /> class with the specified content item of type Brand.
			/// </summary>
			/// <param name="instance">The content item of type Brand that is a target of the extended API.</param>
			public BrandFields(Brand instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BrandCategoryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BrandID;
				}
				set
				{
					mInstance.BrandID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public DocumentAttachment Image
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("Image");
				}
			}


			/// <summary>
			/// Redirection Url.
			/// </summary>
			public string RedirectionUrl
			{
				get
				{
					return mInstance.RedirectionUrl;
				}
				set
				{
					mInstance.RedirectionUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Brand" /> class.
		/// </summary>
		public Brand() : base(CLASS_NAME)
		{
			mFields = new BrandFields(this);
		}

		#endregion
	}
}