//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(BrandCategory.CLASS_NAME, typeof(BrandCategory))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type BrandCategory.
	/// </summary>
	public partial class BrandCategory : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.BrandCategory";


		/// <summary>
		/// The instance of the class that provides extended API for working with BrandCategory fields.
		/// </summary>
		private readonly BrandCategoryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BrandCategoryID.
		/// </summary>
		[DatabaseIDField]
		public int BrandCategoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BrandCategoryID"), 0);
			}
			set
			{
				SetValue("BrandCategoryID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BrandCategory fields.
		/// </summary>
		[RegisterProperty]
		public BrandCategoryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BrandCategory fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BrandCategoryFields : AbstractHierarchicalObject<BrandCategoryFields>
		{
			/// <summary>
			/// The content item of type BrandCategory that is a target of the extended API.
			/// </summary>
			private readonly BrandCategory mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BrandCategoryFields" /> class with the specified content item of type BrandCategory.
			/// </summary>
			/// <param name="instance">The content item of type BrandCategory that is a target of the extended API.</param>
			public BrandCategoryFields(BrandCategory instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BrandCategoryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BrandCategoryID;
				}
				set
				{
					mInstance.BrandCategoryID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BrandCategory" /> class.
		/// </summary>
		public BrandCategory() : base(CLASS_NAME)
		{
			mFields = new BrandCategoryFields(this);
		}

		#endregion
	}
}