//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ProductCategoryTemplateTitle.CLASS_NAME, typeof(ProductCategoryTemplateTitle))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type ProductCategoryTemplateTitle.
	/// </summary>
	public partial class ProductCategoryTemplateTitle : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.ProductCategoryTemplateTitle";


		/// <summary>
		/// The instance of the class that provides extended API for working with ProductCategoryTemplateTitle fields.
		/// </summary>
		private readonly ProductCategoryTemplateTitleFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProductCategoryTemplateTitleID.
		/// </summary>
		[DatabaseIDField]
		public int ProductCategoryTemplateTitleID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProductCategoryTemplateTitleID"), 0);
			}
			set
			{
				SetValue("ProductCategoryTemplateTitleID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string MainTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MainTitle"), @"");
			}
			set
			{
				SetValue("MainTitle", value);
			}
		}


		/// <summary>
		/// Sub category title.
		/// </summary>
		[DatabaseField]
		public string SubCategoryTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SubCategoryTitle"), @"");
			}
			set
			{
				SetValue("SubCategoryTitle", value);
			}
		}


		/// <summary>
		/// Brand Title.
		/// </summary>
		[DatabaseField]
		public string BrandTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrandTitle"), @"");
			}
			set
			{
				SetValue("BrandTitle", value);
			}
		}


		/// <summary>
		/// Resource title.
		/// </summary>
		[DatabaseField]
		public string ResourceTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResourceTitle"), @"");
			}
			set
			{
				SetValue("ResourceTitle", value);
			}
		}


		/// <summary>
		/// Resource description.
		/// </summary>
		[DatabaseField]
		public string ResourceDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResourceDescription"), @"");
			}
			set
			{
				SetValue("ResourceDescription", value);
			}
		}


		/// <summary>
		/// Popup title.
		/// </summary>
		[DatabaseField]
		public string PopupTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PopupTitle"), @"");
			}
			set
			{
				SetValue("PopupTitle", value);
			}
		}


		/// <summary>
		/// TNC Text.
		/// </summary>
		[DatabaseField]
		public string PopupTNCText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PopupTNCText"), @"");
			}
			set
			{
				SetValue("PopupTNCText", value);
			}
		}


		/// <summary>
		/// TNC link Text.
		/// </summary>
		[DatabaseField]
		public string TNCLinkText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TNCLinkText"), @"");
			}
			set
			{
				SetValue("TNCLinkText", value);
			}
		}


		/// <summary>
		/// TNC link url.
		/// </summary>
		[DatabaseField]
		public string TNCLinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TNCLinkUrl"), @"");
			}
			set
			{
				SetValue("TNCLinkUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ProductCategoryTemplateTitle fields.
		/// </summary>
		[RegisterProperty]
		public ProductCategoryTemplateTitleFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ProductCategoryTemplateTitle fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductCategoryTemplateTitleFields : AbstractHierarchicalObject<ProductCategoryTemplateTitleFields>
		{
			/// <summary>
			/// The content item of type ProductCategoryTemplateTitle that is a target of the extended API.
			/// </summary>
			private readonly ProductCategoryTemplateTitle mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductCategoryTemplateTitleFields" /> class with the specified content item of type ProductCategoryTemplateTitle.
			/// </summary>
			/// <param name="instance">The content item of type ProductCategoryTemplateTitle that is a target of the extended API.</param>
			public ProductCategoryTemplateTitleFields(ProductCategoryTemplateTitle instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProductCategoryTemplateTitleID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ProductCategoryTemplateTitleID;
				}
				set
				{
					mInstance.ProductCategoryTemplateTitleID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string MainTitle
			{
				get
				{
					return mInstance.MainTitle;
				}
				set
				{
					mInstance.MainTitle = value;
				}
			}


			/// <summary>
			/// Sub category title.
			/// </summary>
			public string SubCategoryTitle
			{
				get
				{
					return mInstance.SubCategoryTitle;
				}
				set
				{
					mInstance.SubCategoryTitle = value;
				}
			}


			/// <summary>
			/// Brand Title.
			/// </summary>
			public string BrandTitle
			{
				get
				{
					return mInstance.BrandTitle;
				}
				set
				{
					mInstance.BrandTitle = value;
				}
			}


			/// <summary>
			/// Resource title.
			/// </summary>
			public string ResourceTitle
			{
				get
				{
					return mInstance.ResourceTitle;
				}
				set
				{
					mInstance.ResourceTitle = value;
				}
			}


			/// <summary>
			/// Resource description.
			/// </summary>
			public string ResourceDescription
			{
				get
				{
					return mInstance.ResourceDescription;
				}
				set
				{
					mInstance.ResourceDescription = value;
				}
			}


			/// <summary>
			/// Popup title.
			/// </summary>
			public string PopupTitle
			{
				get
				{
					return mInstance.PopupTitle;
				}
				set
				{
					mInstance.PopupTitle = value;
				}
			}


			/// <summary>
			/// TNC Text.
			/// </summary>
			public string PopupTNCText
			{
				get
				{
					return mInstance.PopupTNCText;
				}
				set
				{
					mInstance.PopupTNCText = value;
				}
			}


			/// <summary>
			/// TNC link Text.
			/// </summary>
			public string TNCLinkText
			{
				get
				{
					return mInstance.TNCLinkText;
				}
				set
				{
					mInstance.TNCLinkText = value;
				}
			}


			/// <summary>
			/// TNC link url.
			/// </summary>
			public string TNCLinkUrl
			{
				get
				{
					return mInstance.TNCLinkUrl;
				}
				set
				{
					mInstance.TNCLinkUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ProductCategoryTemplateTitle" /> class.
		/// </summary>
		public ProductCategoryTemplateTitle() : base(CLASS_NAME)
		{
			mFields = new ProductCategoryTemplateTitleFields(this);
		}

		#endregion
	}
}