//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(WhyIngramOption.CLASS_NAME, typeof(WhyIngramOption))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type WhyIngramOption.
	/// </summary>
	public partial class WhyIngramOption : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.WhyIngramOption";


		/// <summary>
		/// The instance of the class that provides extended API for working with WhyIngramOption fields.
		/// </summary>
		private readonly WhyIngramOptionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// WhyIngramSectionID.
		/// </summary>
		[DatabaseIDField]
		public int WhyIngramSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("WhyIngramSectionID"), 0);
			}
			set
			{
				SetValue("WhyIngramSectionID", value);
			}
		}


		/// <summary>
		/// Name Of Navigation Link for Why Ingram Section.
		/// </summary>
		[DatabaseField]
		public string NavigationLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLink"), @"");
			}
			set
			{
				SetValue("NavigationLink", value);
			}
		}


		/// <summary>
		/// Id to navigate in the specific section from the list  of section based on clicked link.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkId
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkId"), @"");
			}
			set
			{
				SetValue("NavigationLinkId", value);
			}
		}


		/// <summary>
		/// BackgroundImage.
		/// </summary>
		[DatabaseField]
		public Guid BackgroundImage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BackgroundImage"), Guid.Empty);
			}
			set
			{
				SetValue("BackgroundImage", value);
			}
		}


		/// <summary>
		/// This heading will be displayed on image as 
		/// heading.
		/// </summary>
		[DatabaseField]
		public string ImageHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageHeading"), @"");
			}
			set
			{
				SetValue("ImageHeading", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WhyIngramOption fields.
		/// </summary>
		[RegisterProperty]
		public WhyIngramOptionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WhyIngramOption fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WhyIngramOptionFields : AbstractHierarchicalObject<WhyIngramOptionFields>
		{
			/// <summary>
			/// The content item of type WhyIngramOption that is a target of the extended API.
			/// </summary>
			private readonly WhyIngramOption mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WhyIngramOptionFields" /> class with the specified content item of type WhyIngramOption.
			/// </summary>
			/// <param name="instance">The content item of type WhyIngramOption that is a target of the extended API.</param>
			public WhyIngramOptionFields(WhyIngramOption instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// WhyIngramSectionID.
			/// </summary>
			public int WhyIngramSectionID
			{
				get
				{
					return mInstance.WhyIngramSectionID;
				}
				set
				{
					mInstance.WhyIngramSectionID = value;
				}
			}


			/// <summary>
			/// Name Of Navigation Link for Why Ingram Section.
			/// </summary>
			public string NavigationLink
			{
				get
				{
					return mInstance.NavigationLink;
				}
				set
				{
					mInstance.NavigationLink = value;
				}
			}


			/// <summary>
			/// Id to navigate in the specific section from the list  of section based on clicked link.
			/// </summary>
			public string NavigationLinkId
			{
				get
				{
					return mInstance.NavigationLinkId;
				}
				set
				{
					mInstance.NavigationLinkId = value;
				}
			}


			/// <summary>
			/// BackgroundImage.
			/// </summary>
			public DocumentAttachment BackgroundImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("BackgroundImage");
				}
			}


			/// <summary>
			/// This heading will be displayed on image as 
			/// heading.
			/// </summary>
			public string ImageHeading
			{
				get
				{
					return mInstance.ImageHeading;
				}
				set
				{
					mInstance.ImageHeading = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WhyIngramOption" /> class.
		/// </summary>
		public WhyIngramOption() : base(CLASS_NAME)
		{
			mFields = new WhyIngramOptionFields(this);
		}

		#endregion
	}
}