//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ActionLink.CLASS_NAME, typeof(ActionLink))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type ActionLink.
	/// </summary>
	public partial class ActionLink : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.ActionLink";


		/// <summary>
		/// The instance of the class that provides extended API for working with ActionLink fields.
		/// </summary>
		private readonly ActionLinkFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SubNavigationID.
		/// </summary>
		[DatabaseIDField]
		public int ActionLinkID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ActionLinkID"), 0);
			}
			set
			{
				SetValue("ActionLinkID", value);
			}
		}


		/// <summary>
		/// Link Text.
		/// </summary>
		[DatabaseField]
		public string ActionLinkItemName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ActionLinkItemName"), @"");
			}
			set
			{
				SetValue("ActionLinkItemName", value);
			}
		}


		/// <summary>
		/// Link Url.
		/// </summary>
		[DatabaseField]
		public string ActionLinkItemUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ActionLinkItemUrl"), @"");
			}
			set
			{
				SetValue("ActionLinkItemUrl", value);
			}
		}


		/// <summary>
		/// Item Icon Class.
		/// </summary>
		[DatabaseField]
		public string ItemIconClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ItemIconClass"), @"");
			}
			set
			{
				SetValue("ItemIconClass", value);
			}
		}


		/// <summary>
		/// Resource Type.
		/// </summary>
		[DatabaseField]
		public string ResourceType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResourceType"), @"");
			}
			set
			{
				SetValue("ResourceType", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ActionLink fields.
		/// </summary>
		[RegisterProperty]
		public ActionLinkFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ActionLink fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ActionLinkFields : AbstractHierarchicalObject<ActionLinkFields>
		{
			/// <summary>
			/// The content item of type ActionLink that is a target of the extended API.
			/// </summary>
			private readonly ActionLink mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ActionLinkFields" /> class with the specified content item of type ActionLink.
			/// </summary>
			/// <param name="instance">The content item of type ActionLink that is a target of the extended API.</param>
			public ActionLinkFields(ActionLink instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SubNavigationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ActionLinkID;
				}
				set
				{
					mInstance.ActionLinkID = value;
				}
			}


			/// <summary>
			/// Link Text.
			/// </summary>
			public string ItemName
			{
				get
				{
					return mInstance.ActionLinkItemName;
				}
				set
				{
					mInstance.ActionLinkItemName = value;
				}
			}


			/// <summary>
			/// Link Url.
			/// </summary>
			public string ItemUrl
			{
				get
				{
					return mInstance.ActionLinkItemUrl;
				}
				set
				{
					mInstance.ActionLinkItemUrl = value;
				}
			}


			/// <summary>
			/// Item Icon Class.
			/// </summary>
			public string ItemIconClass
			{
				get
				{
					return mInstance.ItemIconClass;
				}
				set
				{
					mInstance.ItemIconClass = value;
				}
			}


			/// <summary>
			/// Resource Type.
			/// </summary>
			public string ResourceType
			{
				get
				{
					return mInstance.ResourceType;
				}
				set
				{
					mInstance.ResourceType = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ActionLink" /> class.
		/// </summary>
		public ActionLink() : base(CLASS_NAME)
		{
			mFields = new ActionLinkFields(this);
		}

		#endregion
	}
}