//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.IMABS;

[assembly: RegisterDocumentType(HelpItemTemplate.CLASS_NAME, typeof(HelpItemTemplate))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type HelpItemTemplate.
	/// </summary>
	public partial class HelpItemTemplate : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.HelpItemTemplate";


		/// <summary>
		/// The instance of the class that provides extended API for working with HelpItemTemplate fields.
		/// </summary>
		private readonly HelpItemTemplateFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HelpItemTemplateID.
		/// </summary>
		[DatabaseIDField]
		public int HelpItemTemplateID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HelpItemTemplateID"), 0);
			}
			set
			{
				SetValue("HelpItemTemplateID", value);
			}
		}


		/// <summary>
		/// Page Name.
		/// </summary>
		[DatabaseField]
		public string PageName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PageName"), @"");
			}
			set
			{
				SetValue("PageName", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string Heading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Heading"), @"");
			}
			set
			{
				SetValue("Heading", value);
			}
		}


		/// <summary>
		/// Content.
		/// </summary>
		[DatabaseField]
		public string Content
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Content"), @"");
			}
			set
			{
				SetValue("Content", value);
			}
		}


		/// <summary>
		/// Search Title.
		/// </summary>
		[DatabaseField]
		public string SearchTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SearchTitle"), @"");
			}
			set
			{
				SetValue("SearchTitle", value);
			}
		}


		/// <summary>
		/// Search Placeholder.
		/// </summary>
		[DatabaseField]
		public string SearchPlaceholder
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SearchPlaceholder"), @"");
			}
			set
			{
				SetValue("SearchPlaceholder", value);
			}
		}


		/// <summary>
		/// Search Button Text.
		/// </summary>
		[DatabaseField]
		public string SearchButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SearchButtonText"), @"");
			}
			set
			{
				SetValue("SearchButtonText", value);
			}
		}


		/// <summary>
		/// Enable CTA banner?.
		/// </summary>
		[DatabaseField]
		public bool EnableCallToTactionBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableCallToTactionBanner"), false);
			}
			set
			{
				SetValue("EnableCallToTactionBanner", value);
			}
		}


		/// <summary>
		/// Enable promotions banner?.
		/// </summary>
		[DatabaseField]
		public bool EnablePromotionsBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnablePromotionsBanner"), false);
			}
			set
			{
				SetValue("EnablePromotionsBanner", value);
			}
		}


		/// <summary>
		/// Enable Breadcrumb?.
		/// </summary>
		[DatabaseField]
		public bool EnableBreadcrumb
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableBreadcrumb"), false);
			}
			set
			{
				SetValue("EnableBreadcrumb", value);
			}
		}


		/// <summary>
		/// Show in header menu.
		/// </summary>
		[DatabaseField]
		public bool AllowToViewInHeader
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AllowToViewInHeader"), true);
			}
			set
			{
				SetValue("AllowToViewInHeader", value);
			}
		}


		/// <summary>
		/// Show in footer menu.
		/// </summary>
		[DatabaseField]
		public bool AllowToViewInFooter
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AllowToViewInFooter"), true);
			}
			set
			{
				SetValue("AllowToViewInFooter", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with HelpItemTemplate fields.
		/// </summary>
		[RegisterProperty]
		public HelpItemTemplateFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HelpItemTemplate fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HelpItemTemplateFields : AbstractHierarchicalObject<HelpItemTemplateFields>
		{
			/// <summary>
			/// The content item of type HelpItemTemplate that is a target of the extended API.
			/// </summary>
			private readonly HelpItemTemplate mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HelpItemTemplateFields" /> class with the specified content item of type HelpItemTemplate.
			/// </summary>
			/// <param name="instance">The content item of type HelpItemTemplate that is a target of the extended API.</param>
			public HelpItemTemplateFields(HelpItemTemplate instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HelpItemTemplateID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HelpItemTemplateID;
				}
				set
				{
					mInstance.HelpItemTemplateID = value;
				}
			}


			/// <summary>
			/// Page Name.
			/// </summary>
			public string PageName
			{
				get
				{
					return mInstance.PageName;
				}
				set
				{
					mInstance.PageName = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.Heading;
				}
				set
				{
					mInstance.Heading = value;
				}
			}


			/// <summary>
			/// Content.
			/// </summary>
			public string Content
			{
				get
				{
					return mInstance.Content;
				}
				set
				{
					mInstance.Content = value;
				}
			}


			/// <summary>
			/// Search Title.
			/// </summary>
			public string SearchTitle
			{
				get
				{
					return mInstance.SearchTitle;
				}
				set
				{
					mInstance.SearchTitle = value;
				}
			}


			/// <summary>
			/// Search Placeholder.
			/// </summary>
			public string SearchPlaceholder
			{
				get
				{
					return mInstance.SearchPlaceholder;
				}
				set
				{
					mInstance.SearchPlaceholder = value;
				}
			}


			/// <summary>
			/// Search Button Text.
			/// </summary>
			public string SearchButtonText
			{
				get
				{
					return mInstance.SearchButtonText;
				}
				set
				{
					mInstance.SearchButtonText = value;
				}
			}


			/// <summary>
			/// Enable CTA banner?.
			/// </summary>
			public bool EnableCallToTactionBanner
			{
				get
				{
					return mInstance.EnableCallToTactionBanner;
				}
				set
				{
					mInstance.EnableCallToTactionBanner = value;
				}
			}


			/// <summary>
			/// Enable promotions banner?.
			/// </summary>
			public bool EnablePromotionsBanner
			{
				get
				{
					return mInstance.EnablePromotionsBanner;
				}
				set
				{
					mInstance.EnablePromotionsBanner = value;
				}
			}


			/// <summary>
			/// Enable Breadcrumb?.
			/// </summary>
			public bool EnableBreadcrumb
			{
				get
				{
					return mInstance.EnableBreadcrumb;
				}
				set
				{
					mInstance.EnableBreadcrumb = value;
				}
			}


			/// <summary>
			/// Show in header menu.
			/// </summary>
			public bool AllowToViewInHeader
			{
				get
				{
					return mInstance.AllowToViewInHeader;
				}
				set
				{
					mInstance.AllowToViewInHeader = value;
				}
			}


			/// <summary>
			/// Show in footer menu.
			/// </summary>
			public bool AllowToViewInFooter
			{
				get
				{
					return mInstance.AllowToViewInFooter;
				}
				set
				{
					mInstance.AllowToViewInFooter = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HelpItemTemplate" /> class.
		/// </summary>
		public HelpItemTemplate() : base(CLASS_NAME)
		{
			mFields = new HelpItemTemplateFields(this);
		}

		#endregion
	}
}