
//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(BottomNavigation.CLASS_NAME, typeof(BottomNavigation))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type BottomNavigation.
	/// </summary>
	public partial class BottomNavigation : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.BottomNavigation";


		/// <summary>
		/// The instance of the class that provides extended API for working with BottomNavigation fields.
		/// </summary>
		private readonly BottomNavigationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BottomNavigationID.
		/// </summary>
		[DatabaseIDField]
		public int BottomNavigationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BottomNavigationID"), 0);
			}
			set
			{
				SetValue("BottomNavigationID", value);
			}
		}


		/// <summary>
		/// Bottom Navigation Item Name.
		/// </summary>
		[DatabaseField]
		public string NavigationItemName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationItemName"), @"");
			}
			set
			{
				SetValue("NavigationItemName", value);
			}
		}


		/// <summary>
		/// Bottom Navigation Item URL.
		/// </summary>
		[DatabaseField]
		public string NavigationItemUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationItemUrl"), @"");
			}
			set
			{
				SetValue("NavigationItemUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BottomNavigation fields.
		/// </summary>
		[RegisterProperty]
		public BottomNavigationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BottomNavigation fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BottomNavigationFields : AbstractHierarchicalObject<BottomNavigationFields>
		{
			/// <summary>
			/// The content item of type BottomNavigation that is a target of the extended API.
			/// </summary>
			private readonly BottomNavigation mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BottomNavigationFields" /> class with the specified content item of type BottomNavigation.
			/// </summary>
			/// <param name="instance">The content item of type BottomNavigation that is a target of the extended API.</param>
			public BottomNavigationFields(BottomNavigation instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BottomNavigationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BottomNavigationID;
				}
				set
				{
					mInstance.BottomNavigationID = value;
				}
			}


			/// <summary>
			/// Bottom Navigation Item Name.
			/// </summary>
			public string NavigationItemName
			{
				get
				{
					return mInstance.NavigationItemName;
				}
				set
				{
					mInstance.NavigationItemName = value;
				}
			}


			/// <summary>
			/// Bottom Navigation Item URL.
			/// </summary>
			public string NavigationItemUrl
			{
				get
				{
					return mInstance.NavigationItemUrl;
				}
				set
				{
					mInstance.NavigationItemUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BottomNavigation" /> class.
		/// </summary>
		public BottomNavigation() : base(CLASS_NAME)
		{
			mFields = new BottomNavigationFields(this);
		}

		#endregion
	}
}