//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ResourceLink.CLASS_NAME, typeof(ResourceLink))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type ResourceLink.
	/// </summary>
	public partial class ResourceLink : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.ResourceLink";


		/// <summary>
		/// The instance of the class that provides extended API for working with ResourceLink fields.
		/// </summary>
		private readonly ResourceLinkFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SubNavigationID.
		/// </summary>
		[DatabaseIDField]
		public int ResourceLinkID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ResourceLinkID"), 0);
			}
			set
			{
				SetValue("ResourceLinkID", value);
			}
		}


		/// <summary>
		/// Resource category.
		/// </summary>
		[DatabaseField]
		public string Resource
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Resource"), @"");
			}
			set
			{
				SetValue("Resource", value);
			}
		}


		/// <summary>
		/// Link Text.
		/// </summary>
		[DatabaseField]
		public string ActionLinkItemName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ActionLinkItemName"), @"");
			}
			set
			{
				SetValue("ActionLinkItemName", value);
			}
		}


		/// <summary>
		/// Link Url.
		/// </summary>
		[DatabaseField]
		public string ActionLinkItemUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ActionLinkItemUrl"), @"");
			}
			set
			{
				SetValue("ActionLinkItemUrl", value);
			}
		}


		/// <summary>
		/// Attachment.
		/// </summary>
		[DatabaseField]
		public Guid ResourcePath
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("ResourcePath"), Guid.Empty);
			}
			set
			{
				SetValue("ResourcePath", value);
			}
		}


		/// <summary>
		/// Window target.
		/// </summary>
		[DatabaseField]
		public string WindowTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WindowTarget"), @"");
			}
			set
			{
				SetValue("WindowTarget", value);
			}
		}


		/// <summary>
		/// Resource Type.
		/// </summary>
		[DatabaseField]
		public string ResourceType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResourceType"), @"");
			}
			set
			{
				SetValue("ResourceType", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ResourceLink fields.
		/// </summary>
		[RegisterProperty]
		public ResourceLinkFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ResourceLink fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ResourceLinkFields : AbstractHierarchicalObject<ResourceLinkFields>
		{
			/// <summary>
			/// The content item of type ResourceLink that is a target of the extended API.
			/// </summary>
			private readonly ResourceLink mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ResourceLinkFields" /> class with the specified content item of type ResourceLink.
			/// </summary>
			/// <param name="instance">The content item of type ResourceLink that is a target of the extended API.</param>
			public ResourceLinkFields(ResourceLink instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SubNavigationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ResourceLinkID;
				}
				set
				{
					mInstance.ResourceLinkID = value;
				}
			}


			/// <summary>
			/// Resource category.
			/// </summary>
			public string Resource
			{
				get
				{
					return mInstance.Resource;
				}
				set
				{
					mInstance.Resource = value;
				}
			}


			/// <summary>
			/// Link Text.
			/// </summary>
			public string ActionLinkItemName
			{
				get
				{
					return mInstance.ActionLinkItemName;
				}
				set
				{
					mInstance.ActionLinkItemName = value;
				}
			}


			/// <summary>
			/// Link Url.
			/// </summary>
			public string ActionLinkItemUrl
			{
				get
				{
					return mInstance.ActionLinkItemUrl;
				}
				set
				{
					mInstance.ActionLinkItemUrl = value;
				}
			}


			/// <summary>
			/// Attachment.
			/// </summary>
			public DocumentAttachment ResourcePath
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("ResourcePath");
				}
			}


			/// <summary>
			/// Window target.
			/// </summary>
			public string WindowTarget
			{
				get
				{
					return mInstance.WindowTarget;
				}
				set
				{
					mInstance.WindowTarget = value;
				}
			}


			/// <summary>
			/// Resource Type.
			/// </summary>
			public string ResourceType
			{
				get
				{
					return mInstance.ResourceType;
				}
				set
				{
					mInstance.ResourceType = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ResourceLink" /> class.
		/// </summary>
		public ResourceLink() : base(CLASS_NAME)
		{
			mFields = new ResourceLinkFields(this);
		}

		#endregion
	}
}