//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.IMABS;

[assembly: RegisterDocumentType(Help.CLASS_NAME, typeof(Help))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type Help.
	/// </summary>
	public partial class Help : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.Help";


		/// <summary>
		/// The instance of the class that provides extended API for working with Help fields.
		/// </summary>
		private readonly HelpFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HelpID.
		/// </summary>
		[DatabaseIDField]
		public int HelpID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HelpID"), 0);
			}
			set
			{
				SetValue("HelpID", value);
			}
		}


		/// <summary>
		/// Page Name.
		/// </summary>
		[DatabaseField]
		public string PageName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PageName"), @"");
			}
			set
			{
				SetValue("PageName", value);
			}
		}


		/// <summary>
		/// Search Placeholder Text.
		/// </summary>
		[DatabaseField]
		public string SearchPlaceholderText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SearchPlaceholderText"), @"");
			}
			set
			{
				SetValue("SearchPlaceholderText", value);
			}
		}


		/// <summary>
		/// Search Button Text.
		/// </summary>
		[DatabaseField]
		public string SearchButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SearchButtonText"), @"");
			}
			set
			{
				SetValue("SearchButtonText", value);
			}
		}


		/// <summary>
		/// Enable CTA banner?.
		/// </summary>
		[DatabaseField]
		public bool EnableCallToTactionBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableCallToTactionBanner"), false);
			}
			set
			{
				SetValue("EnableCallToTactionBanner", value);
			}
		}


		/// <summary>
		/// Enable promotions banner?.
		/// </summary>
		[DatabaseField]
		public bool EnablePromotionsBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnablePromotionsBanner"), false);
			}
			set
			{
				SetValue("EnablePromotionsBanner", value);
			}
		}


		/// <summary>
		/// Enable Breadcrumb?.
		/// </summary>
		[DatabaseField]
		public bool EnableBreadcrumb
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableBreadcrumb"), false);
			}
			set
			{
				SetValue("EnableBreadcrumb", value);
			}
		}


		/// <summary>
		/// Show in header menu.
		/// </summary>
		[DatabaseField]
		public bool AllowToViewInHeader
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AllowToViewInHeader"), true);
			}
			set
			{
				SetValue("AllowToViewInHeader", value);
			}
		}


		/// <summary>
		/// Show in footer menu.
		/// </summary>
		[DatabaseField]
		public bool AllowToViewInFooter
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AllowToViewInFooter"), true);
			}
			set
			{
				SetValue("AllowToViewInFooter", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Help fields.
		/// </summary>
		[RegisterProperty]
		public HelpFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Help fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HelpFields : AbstractHierarchicalObject<HelpFields>
		{
			/// <summary>
			/// The content item of type Help that is a target of the extended API.
			/// </summary>
			private readonly Help mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HelpFields" /> class with the specified content item of type Help.
			/// </summary>
			/// <param name="instance">The content item of type Help that is a target of the extended API.</param>
			public HelpFields(Help instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HelpID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HelpID;
				}
				set
				{
					mInstance.HelpID = value;
				}
			}


			/// <summary>
			/// Page Name.
			/// </summary>
			public string PageName
			{
				get
				{
					return mInstance.PageName;
				}
				set
				{
					mInstance.PageName = value;
				}
			}


			/// <summary>
			/// Search Placeholder Text.
			/// </summary>
			public string SearchPlaceholderText
			{
				get
				{
					return mInstance.SearchPlaceholderText;
				}
				set
				{
					mInstance.SearchPlaceholderText = value;
				}
			}


			/// <summary>
			/// Search Button Text.
			/// </summary>
			public string SearchButtonText
			{
				get
				{
					return mInstance.SearchButtonText;
				}
				set
				{
					mInstance.SearchButtonText = value;
				}
			}


			/// <summary>
			/// Enable CTA banner?.
			/// </summary>
			public bool EnableCallToTactionBanner
			{
				get
				{
					return mInstance.EnableCallToTactionBanner;
				}
				set
				{
					mInstance.EnableCallToTactionBanner = value;
				}
			}


			/// <summary>
			/// Enable promotions banner?.
			/// </summary>
			public bool EnablePromotionsBanner
			{
				get
				{
					return mInstance.EnablePromotionsBanner;
				}
				set
				{
					mInstance.EnablePromotionsBanner = value;
				}
			}


			/// <summary>
			/// Enable Breadcrumb?.
			/// </summary>
			public bool EnableBreadcrumb
			{
				get
				{
					return mInstance.EnableBreadcrumb;
				}
				set
				{
					mInstance.EnableBreadcrumb = value;
				}
			}


			/// <summary>
			/// Show in header menu.
			/// </summary>
			public bool AllowToViewInHeader
			{
				get
				{
					return mInstance.AllowToViewInHeader;
				}
				set
				{
					mInstance.AllowToViewInHeader = value;
				}
			}


			/// <summary>
			/// Show in footer menu.
			/// </summary>
			public bool AllowToViewInFooter
			{
				get
				{
					return mInstance.AllowToViewInFooter;
				}
				set
				{
					mInstance.AllowToViewInFooter = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Help" /> class.
		/// </summary>
		public Help() : base(CLASS_NAME)
		{
			mFields = new HelpFields(this);
		}

		#endregion
	}
}