//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PartnerCentral.CLASS_NAME, typeof(PartnerCentral))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type PartnerCentral.
	/// </summary>
	public partial class PartnerCentral : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.PartnerCentral";


		/// <summary>
		/// The instance of the class that provides extended API for working with PartnerCentral fields.
		/// </summary>
		private readonly PartnerCentralFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PartnerCentralID.
		/// </summary>
		[DatabaseIDField]
		public int PartnerCentralID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PartnerCentralID"), 0);
			}
			set
			{
				SetValue("PartnerCentralID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Sub Title.
		/// </summary>
		[DatabaseField]
		public string SubTItle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SubTItle"), @"");
			}
			set
			{
				SetValue("SubTItle", value);
			}
		}


		/// <summary>
		/// CTA Button Text.
		/// </summary>
		[DatabaseField]
		public string CTAButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CTAButtonText"), @"");
			}
			set
			{
				SetValue("CTAButtonText", value);
			}
		}


		/// <summary>
		/// CTA Button Link.
		/// </summary>
		[DatabaseField]
		public string CTAButtonLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CTAButtonLink"), @"");
			}
			set
			{
				SetValue("CTAButtonLink", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public Guid Image
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Image"), Guid.Empty);
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PartnerCentral fields.
		/// </summary>
		[RegisterProperty]
		public PartnerCentralFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PartnerCentral fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PartnerCentralFields : AbstractHierarchicalObject<PartnerCentralFields>
		{
			/// <summary>
			/// The content item of type PartnerCentral that is a target of the extended API.
			/// </summary>
			private readonly PartnerCentral mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PartnerCentralFields" /> class with the specified content item of type PartnerCentral.
			/// </summary>
			/// <param name="instance">The content item of type PartnerCentral that is a target of the extended API.</param>
			public PartnerCentralFields(PartnerCentral instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PartnerCentralID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PartnerCentralID;
				}
				set
				{
					mInstance.PartnerCentralID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Sub Title.
			/// </summary>
			public string SubTItle
			{
				get
				{
					return mInstance.SubTItle;
				}
				set
				{
					mInstance.SubTItle = value;
				}
			}


			/// <summary>
			/// CTA Button Text.
			/// </summary>
			public string CTAButtonText
			{
				get
				{
					return mInstance.CTAButtonText;
				}
				set
				{
					mInstance.CTAButtonText = value;
				}
			}


			/// <summary>
			/// CTA Button Link.
			/// </summary>
			public string CTAButtonLink
			{
				get
				{
					return mInstance.CTAButtonLink;
				}
				set
				{
					mInstance.CTAButtonLink = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public DocumentAttachment Image
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("Image");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PartnerCentral" /> class.
		/// </summary>
		public PartnerCentral() : base(CLASS_NAME)
		{
			mFields = new PartnerCentralFields(this);
		}

		#endregion
	}
}