//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(BannerSection.CLASS_NAME, typeof(BannerSection))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type BannerSection.
	/// </summary>
	public partial class BannerSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.BannerSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with BannerSection fields.
		/// </summary>
		private readonly BannerSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BannerSectionID.
		/// </summary>
		[DatabaseIDField]
		public int BannerSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BannerSectionID"), 0);
			}
			set
			{
				SetValue("BannerSectionID", value);
			}
		}


		/// <summary>
		/// Heading of banner.
		/// </summary>
		[DatabaseField]
		public string BannerHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerHeading"), @"");
			}
			set
			{
				SetValue("BannerHeading", value);
			}
		}


		/// <summary>
		/// breadcrumbs name of the banner to be display on website.
		/// </summary>
		[DatabaseField]
		public string BannerBreadcrumbsTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerBreadcrumbsTitle"), @"");
			}
			set
			{
				SetValue("BannerBreadcrumbsTitle", value);
			}
		}


		/// <summary>
		/// Check this check box if you want to display this banner in website UI.
		/// </summary>
		[DatabaseField]
		public bool IsActiveBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsActiveBanner"), true);
			}
			set
			{
				SetValue("IsActiveBanner", value);
			}
		}


		/// <summary>
		/// Banner Image.
		/// </summary>
		[DatabaseField]
		public Guid BannerImage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BannerImage"), Guid.Empty);
			}
			set
			{
				SetValue("BannerImage", value);
			}
		}


		/// <summary>
		/// Name to be display on website for load more button in  banner section.
		/// </summary>
		[DatabaseField]
		public string ButtonLinkName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonLinkName"), @"");
			}
			set
			{
				SetValue("ButtonLinkName", value);
			}
		}


		/// <summary>
		/// Page name on which you need to redirect when user click on it.
		/// </summary>
		[DatabaseField]
		public string ButtonRedirectionUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonRedirectionUrl"), @"");
			}
			set
			{
				SetValue("ButtonRedirectionUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BannerSection fields.
		/// </summary>
		[RegisterProperty]
		public BannerSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BannerSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BannerSectionFields : AbstractHierarchicalObject<BannerSectionFields>
		{
			/// <summary>
			/// The content item of type BannerSection that is a target of the extended API.
			/// </summary>
			private readonly BannerSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BannerSectionFields" /> class with the specified content item of type BannerSection.
			/// </summary>
			/// <param name="instance">The content item of type BannerSection that is a target of the extended API.</param>
			public BannerSectionFields(BannerSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BannerSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BannerSectionID;
				}
				set
				{
					mInstance.BannerSectionID = value;
				}
			}


			/// <summary>
			/// Heading of banner.
			/// </summary>
			public string BannerHeading
			{
				get
				{
					return mInstance.BannerHeading;
				}
				set
				{
					mInstance.BannerHeading = value;
				}
			}


			/// <summary>
			/// breadcrumbs name of the banner to be display on website.
			/// </summary>
			public string BannerBreadcrumbsTitle
			{
				get
				{
					return mInstance.BannerBreadcrumbsTitle;
				}
				set
				{
					mInstance.BannerBreadcrumbsTitle = value;
				}
			}


			/// <summary>
			/// Check this check box if you want to display this banner in website UI.
			/// </summary>
			public bool IsActiveBanner
			{
				get
				{
					return mInstance.IsActiveBanner;
				}
				set
				{
					mInstance.IsActiveBanner = value;
				}
			}


			/// <summary>
			/// Banner Image.
			/// </summary>
			public DocumentAttachment BannerImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("BannerImage");
				}
			}


			/// <summary>
			/// Name to be display on website for load more button in  banner section.
			/// </summary>
			public string ButtonLinkName
			{
				get
				{
					return mInstance.ButtonLinkName;
				}
				set
				{
					mInstance.ButtonLinkName = value;
				}
			}


			/// <summary>
			/// Page name on which you need to redirect when user click on it.
			/// </summary>
			public string ButtonRedirectionUrl
			{
				get
				{
					return mInstance.ButtonRedirectionUrl;
				}
				set
				{
					mInstance.ButtonRedirectionUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BannerSection" /> class.
		/// </summary>
		public BannerSection() : base(CLASS_NAME)
		{
			mFields = new BannerSectionFields(this);
		}

		#endregion
	}
}