//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ProductSubCategory.CLASS_NAME, typeof(ProductSubCategory))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type ProductSubCategory.
	/// </summary>
	public partial class ProductSubCategory : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.ProductSubCategory";


		/// <summary>
		/// The instance of the class that provides extended API for working with ProductSubCategory fields.
		/// </summary>
		private readonly ProductSubCategoryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CategoryIndexID.
		/// </summary>
		[DatabaseIDField]
		public int ProductSubCategoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProductSubCategoryID"), 0);
			}
			set
			{
				SetValue("ProductSubCategoryID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ProductSubCategory fields.
		/// </summary>
		[RegisterProperty]
		public ProductSubCategoryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ProductSubCategory fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductSubCategoryFields : AbstractHierarchicalObject<ProductSubCategoryFields>
		{
			/// <summary>
			/// The content item of type ProductSubCategory that is a target of the extended API.
			/// </summary>
			private readonly ProductSubCategory mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductSubCategoryFields" /> class with the specified content item of type ProductSubCategory.
			/// </summary>
			/// <param name="instance">The content item of type ProductSubCategory that is a target of the extended API.</param>
			public ProductSubCategoryFields(ProductSubCategory instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CategoryIndexID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ProductSubCategoryID;
				}
				set
				{
					mInstance.ProductSubCategoryID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ProductSubCategory" /> class.
		/// </summary>
		public ProductSubCategory() : base(CLASS_NAME)
		{
			mFields = new ProductSubCategoryFields(this);
		}

		#endregion
	}
}