//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.IMABS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Privacy.CLASS_NAME, typeof(Privacy))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type Privacy.
	/// </summary>
	public partial class Privacy : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.Privacy";


		/// <summary>
		/// The instance of the class that provides extended API for working with Privacy fields.
		/// </summary>
		private readonly PrivacyFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PrivacyID.
		/// </summary>
		[DatabaseIDField]
		public int PrivacyID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PrivacyID"), 0);
			}
			set
			{
				SetValue("PrivacyID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string Heading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Heading"), @"");
			}
			set
			{
				SetValue("Heading", value);
			}
		}


		/// <summary>
		/// Content.
		/// </summary>
		[DatabaseField]
		public string Content
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Content"), @"");
			}
			set
			{
				SetValue("Content", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Privacy fields.
		/// </summary>
		[RegisterProperty]
		public PrivacyFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Privacy fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PrivacyFields : AbstractHierarchicalObject<PrivacyFields>
		{
			/// <summary>
			/// The content item of type Privacy that is a target of the extended API.
			/// </summary>
			private readonly Privacy mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PrivacyFields" /> class with the specified content item of type Privacy.
			/// </summary>
			/// <param name="instance">The content item of type Privacy that is a target of the extended API.</param>
			public PrivacyFields(Privacy instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PrivacyID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PrivacyID;
				}
				set
				{
					mInstance.PrivacyID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.Heading;
				}
				set
				{
					mInstance.Heading = value;
				}
			}


			/// <summary>
			/// Content.
			/// </summary>
			public string Content
			{
				get
				{
					return mInstance.Content;
				}
				set
				{
					mInstance.Content = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Privacy" /> class.
		/// </summary>
		public Privacy() : base(CLASS_NAME)
		{
			mFields = new PrivacyFields(this);
		}

		#endregion
	}
}