//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.IMABS;

[assembly: RegisterDocumentType(BecomePartner.CLASS_NAME, typeof(BecomePartner))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type BecomePartner.
	/// </summary>
	public partial class BecomePartner : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.BecomePartner";


		/// <summary>
		/// The instance of the class that provides extended API for working with BecomePartner fields.
		/// </summary>
		private readonly BecomePartnerFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BecomePartnerID.
		/// </summary>
		[DatabaseIDField]
		public int BecomePartnerID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BecomePartnerID"), 0);
			}
			set
			{
				SetValue("BecomePartnerID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// ApplyTitle.
		/// </summary>
		[DatabaseField]
		public string ApplyTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplyTitle"), @"");
			}
			set
			{
				SetValue("ApplyTitle", value);
			}
		}


		/// <summary>
		/// Apply Description.
		/// </summary>
		[DatabaseField]
		public string ApplyDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplyDescription"), @"");
			}
			set
			{
				SetValue("ApplyDescription", value);
			}
		}


		/// <summary>
		/// Apply Rules.
		/// </summary>
		[DatabaseField]
		public string ApplyRules
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplyRules"), @"");
			}
			set
			{
				SetValue("ApplyRules", value);
			}
		}


		/// <summary>
		/// Apply Notes Title.
		/// </summary>
		[DatabaseField]
		public string ApplyNotesTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplyNotesTitle"), @"");
			}
			set
			{
				SetValue("ApplyNotesTitle", value);
			}
		}


		/// <summary>
		/// Apply Notes Rules.
		/// </summary>
		[DatabaseField]
		public string ApplyNotesRules
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplyNotesRules"), @"");
			}
			set
			{
				SetValue("ApplyNotesRules", value);
			}
		}


		/// <summary>
		/// CTA Banner.
		/// </summary>
		[DatabaseField]
		public string CTABanner
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CTABanner"), @"");
			}
			set
			{
				SetValue("CTABanner", value);
			}
		}


		/// <summary>
		/// Enable CTA banner?.
		/// </summary>
		[DatabaseField]
		public bool EnableCallToTactionBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableCallToTactionBanner"), false);
			}
			set
			{
				SetValue("EnableCallToTactionBanner", value);
			}
		}


		/// <summary>
		/// Enable promotions banner?.
		/// </summary>
		[DatabaseField]
		public bool EnablePromotionsBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnablePromotionsBanner"), false);
			}
			set
			{
				SetValue("EnablePromotionsBanner", value);
			}
		}


		/// <summary>
		/// Enable Breadcrumb?.
		/// </summary>
		[DatabaseField]
		public bool EnableBreadcrumb
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableBreadcrumb"), false);
			}
			set
			{
				SetValue("EnableBreadcrumb", value);
			}
		}


		/// <summary>
		/// Show in header menu.
		/// </summary>
		[DatabaseField]
		public bool AllowToViewInHeader
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AllowToViewInHeader"), true);
			}
			set
			{
				SetValue("AllowToViewInHeader", value);
			}
		}


		/// <summary>
		/// Show in footer menu.
		/// </summary>
		[DatabaseField]
		public bool AllowToViewInFooter
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AllowToViewInFooter"), true);
			}
			set
			{
				SetValue("AllowToViewInFooter", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BecomePartner fields.
		/// </summary>
		[RegisterProperty]
		public BecomePartnerFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BecomePartner fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BecomePartnerFields : AbstractHierarchicalObject<BecomePartnerFields>
		{
			/// <summary>
			/// The content item of type BecomePartner that is a target of the extended API.
			/// </summary>
			private readonly BecomePartner mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BecomePartnerFields" /> class with the specified content item of type BecomePartner.
			/// </summary>
			/// <param name="instance">The content item of type BecomePartner that is a target of the extended API.</param>
			public BecomePartnerFields(BecomePartner instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BecomePartnerID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BecomePartnerID;
				}
				set
				{
					mInstance.BecomePartnerID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// ApplyTitle.
			/// </summary>
			public string ApplyTitle
			{
				get
				{
					return mInstance.ApplyTitle;
				}
				set
				{
					mInstance.ApplyTitle = value;
				}
			}


			/// <summary>
			/// Apply Description.
			/// </summary>
			public string ApplyDescription
			{
				get
				{
					return mInstance.ApplyDescription;
				}
				set
				{
					mInstance.ApplyDescription = value;
				}
			}


			/// <summary>
			/// Apply Rules.
			/// </summary>
			public string ApplyRules
			{
				get
				{
					return mInstance.ApplyRules;
				}
				set
				{
					mInstance.ApplyRules = value;
				}
			}


			/// <summary>
			/// Apply Notes Title.
			/// </summary>
			public string ApplyNotesTitle
			{
				get
				{
					return mInstance.ApplyNotesTitle;
				}
				set
				{
					mInstance.ApplyNotesTitle = value;
				}
			}


			/// <summary>
			/// Apply Notes Rules.
			/// </summary>
			public string ApplyNotesRules
			{
				get
				{
					return mInstance.ApplyNotesRules;
				}
				set
				{
					mInstance.ApplyNotesRules = value;
				}
			}


			/// <summary>
			/// CTA Banner.
			/// </summary>
			public string CTABanner
			{
				get
				{
					return mInstance.CTABanner;
				}
				set
				{
					mInstance.CTABanner = value;
				}
			}


			/// <summary>
			/// Enable CTA banner?.
			/// </summary>
			public bool EnableCallToTactionBanner
			{
				get
				{
					return mInstance.EnableCallToTactionBanner;
				}
				set
				{
					mInstance.EnableCallToTactionBanner = value;
				}
			}


			/// <summary>
			/// Enable promotions banner?.
			/// </summary>
			public bool EnablePromotionsBanner
			{
				get
				{
					return mInstance.EnablePromotionsBanner;
				}
				set
				{
					mInstance.EnablePromotionsBanner = value;
				}
			}


			/// <summary>
			/// Enable Breadcrumb?.
			/// </summary>
			public bool EnableBreadcrumb
			{
				get
				{
					return mInstance.EnableBreadcrumb;
				}
				set
				{
					mInstance.EnableBreadcrumb = value;
				}
			}


			/// <summary>
			/// Show in header menu.
			/// </summary>
			public bool AllowToViewInHeader
			{
				get
				{
					return mInstance.AllowToViewInHeader;
				}
				set
				{
					mInstance.AllowToViewInHeader = value;
				}
			}


			/// <summary>
			/// Show in footer menu.
			/// </summary>
			public bool AllowToViewInFooter
			{
				get
				{
					return mInstance.AllowToViewInFooter;
				}
				set
				{
					mInstance.AllowToViewInFooter = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BecomePartner" /> class.
		/// </summary>
		public BecomePartner() : base(CLASS_NAME)
		{
			mFields = new BecomePartnerFields(this);
		}

		#endregion
	}
}