//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.IMABS;

[assembly: RegisterDocumentType(AccordionItem.CLASS_NAME, typeof(AccordionItem))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type AccordionItem.
	/// </summary>
	public partial class AccordionItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.AccordionItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with AccordionItem fields.
		/// </summary>
		private readonly AccordionItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AccordionItemID.
		/// </summary>
		[DatabaseIDField]
		public int AccordionItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AccordionItemID"), 0);
			}
			set
			{
				SetValue("AccordionItemID", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string Heading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Heading"), @"");
			}
			set
			{
				SetValue("Heading", value);
			}
		}


		/// <summary>
		/// Content.
		/// </summary>
		[DatabaseField]
		public string Content
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Content"), @"");
			}
			set
			{
				SetValue("Content", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AccordionItem fields.
		/// </summary>
		[RegisterProperty]
		public AccordionItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AccordionItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AccordionItemFields : AbstractHierarchicalObject<AccordionItemFields>
		{
			/// <summary>
			/// The content item of type AccordionItem that is a target of the extended API.
			/// </summary>
			private readonly AccordionItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AccordionItemFields" /> class with the specified content item of type AccordionItem.
			/// </summary>
			/// <param name="instance">The content item of type AccordionItem that is a target of the extended API.</param>
			public AccordionItemFields(AccordionItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AccordionItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AccordionItemID;
				}
				set
				{
					mInstance.AccordionItemID = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.Heading;
				}
				set
				{
					mInstance.Heading = value;
				}
			}


			/// <summary>
			/// Content.
			/// </summary>
			public string Content
			{
				get
				{
					return mInstance.Content;
				}
				set
				{
					mInstance.Content = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AccordionItem" /> class.
		/// </summary>
		public AccordionItem() : base(CLASS_NAME)
		{
			mFields = new AccordionItemFields(this);
		}

		#endregion
	}
}